import { LanguageSpec } from './tokenizer';

/**
 * Language registry.
 *
 * Everything here is data. Adding a language is a dozen lines, which is the
 * point - the alternative is a hand-written grammar each time and nobody would
 * ever add the eightieth one.
 *
 * Bias is deliberately toward what people actually open in a game panel:
 * configs, scripts and logs, with general-purpose languages behind them.
 */

// Shared keyword sets, since the C family overlaps heavily and duplicating
// these is how they drift apart.
const C_LIKE = ['if', 'else', 'for', 'while', 'do', 'switch', 'case', 'default', 'break', 'continue', 'return', 'goto'];
const ACCESS = ['public', 'private', 'protected', 'static', 'final', 'abstract', 'const', 'readonly'];
const BOOLEANS = ['true', 'false', 'null'];

const slashComments = { lineComment: ['//'], blockComment: ['/*', '*/'] as [string, string] };
const hashComment = { lineComment: ['#'] };
const quotes = { quotes: ['"', "'"], escapes: true };

const languages: LanguageSpec[] = [
    // ---- Configuration -----------------------------------------------------
    {
        id: 'json',
        name: 'JSON',
        extensions: ['json', 'json5', 'jsonc', 'map', 'lock', 'webmanifest'],
        ...slashComments,
        quotes: ['"'],
        escapes: true,
        constants: BOOLEANS,
    },
    {
        id: 'yaml',
        name: 'YAML',
        extensions: ['yml', 'yaml'],
        ...hashComment,
        ...quotes,
        constants: [...BOOLEANS, 'yes', 'no', 'on', 'off', '~'],
        caseInsensitive: true,
    },
    {
        id: 'toml',
        name: 'TOML',
        extensions: ['toml'],
        ...hashComment,
        quotes: ['"', "'"],
        multilineQuotes: ['"""', "'''"],
        escapes: true,
        constants: BOOLEANS,
    },
    {
        id: 'properties',
        name: 'Properties',
        // server.properties is the single most edited file on a Minecraft host.
        extensions: ['properties', 'ini', 'cfg', 'conf', 'env', 'in'],
        lineComment: ['#', ';', '!'],
        quotes: ['"', "'"],
        constants: [...BOOLEANS, 'yes', 'no', 'on', 'off'],
        caseInsensitive: true,
    },
    {
        id: 'nginx',
        name: 'Nginx',
        extensions: ['nginx'],
        filenames: [/^nginx.*\.conf$/i],
        ...hashComment,
        ...quotes,
        keywords: ['server', 'location', 'upstream', 'http', 'events', 'listen', 'include', 'proxy_pass', 'root'],
        constants: ['on', 'off'],
    },
    {
        id: 'hcl',
        name: 'HCL / Terraform',
        extensions: ['hcl', 'tf', 'tfvars'],
        lineComment: ['#', '//'],
        blockComment: ['/*', '*/'],
        ...quotes,
        keywords: ['resource', 'variable', 'provider', 'module', 'output', 'data', 'locals', 'terraform'],
        constants: BOOLEANS,
    },
    {
        id: 'dockerfile',
        name: 'Dockerfile',
        extensions: ['dockerfile'],
        filenames: [/^Dockerfile(\..+)?$/i, /^Containerfile$/i],
        ...hashComment,
        ...quotes,
        keywords: [
            'FROM',
            'RUN',
            'CMD',
            'LABEL',
            'EXPOSE',
            'ENV',
            'ADD',
            'COPY',
            'ENTRYPOINT',
            'VOLUME',
            'USER',
            'WORKDIR',
            'ARG',
            'ONBUILD',
            'HEALTHCHECK',
            'SHELL',
            'AS',
        ],
        caseInsensitive: true,
    },

    // ---- Shell -------------------------------------------------------------
    {
        id: 'shell',
        name: 'Shell',
        extensions: ['sh', 'bash', 'zsh', 'ksh', 'fish'],
        filenames: [/^PKGBUILD$/, /^\.bashrc$/, /^\.zshrc$/],
        ...hashComment,
        ...quotes,
        identifier: /[A-Za-z_$][\w$]*/y,
        keywords: [
            'if',
            'then',
            'else',
            'elif',
            'fi',
            'for',
            'while',
            'do',
            'done',
            'case',
            'esac',
            'function',
            'in',
            'select',
            'until',
            'return',
            'exit',
        ],
        builtins: [
            'echo',
            'cd',
            'export',
            'source',
            'read',
            'set',
            'unset',
            'local',
            'sudo',
            'chmod',
            'chown',
            'mkdir',
            'rm',
            'cp',
            'mv',
            'cat',
            'grep',
            'sed',
            'awk',
            'curl',
            'wget',
            'tar',
        ],
    },
    {
        id: 'powershell',
        name: 'PowerShell',
        extensions: ['ps1', 'psm1', 'psd1'],
        ...hashComment,
        blockComment: ['<#', '#>'],
        ...quotes,
        keywords: [
            'if',
            'else',
            'elseif',
            'foreach',
            'for',
            'while',
            'do',
            'switch',
            'function',
            'return',
            'try',
            'catch',
            'finally',
            'param',
            'begin',
            'process',
            'end',
        ],
        constants: ['$true', '$false', '$null'],
        caseInsensitive: true,
    },
    {
        id: 'batch',
        name: 'Batch',
        extensions: ['bat', 'cmd'],
        lineComment: ['REM', '::'],
        quotes: ['"'],
        keywords: ['if', 'else', 'for', 'goto', 'call', 'set', 'echo', 'exit', 'pause', 'setlocal', 'endlocal'],
        caseInsensitive: true,
    },

    // ---- Scripting ---------------------------------------------------------
    {
        id: 'lua',
        name: 'Lua',
        // FiveM runs on this, so it matters more here than its general
        // popularity would suggest.
        extensions: ['lua'],
        lineComment: ['--'],
        blockComment: ['--[[', ']]'],
        ...quotes,
        keywords: [
            'and',
            'break',
            'do',
            'else',
            'elseif',
            'end',
            'for',
            'function',
            'goto',
            'if',
            'in',
            'local',
            'not',
            'or',
            'repeat',
            'return',
            'then',
            'until',
            'while',
        ],
        builtins: [
            'print',
            'pairs',
            'ipairs',
            'require',
            'pcall',
            'type',
            'tostring',
            'tonumber',
            'setmetatable',
            'table',
            'string',
            'math',
            'os',
            'io',
            'Citizen',
            'RegisterCommand',
            'TriggerEvent',
            'AddEventHandler',
        ],
        constants: ['true', 'false', 'nil'],
    },
    {
        id: 'javascript',
        name: 'JavaScript',
        extensions: ['js', 'mjs', 'cjs', 'jsx'],
        ...slashComments,
        quotes: ['"', "'", '`'],
        escapes: true,
        keywords: [
            ...C_LIKE,
            'const',
            'let',
            'var',
            'function',
            'class',
            'extends',
            'new',
            'this',
            'super',
            'import',
            'export',
            'from',
            'as',
            'async',
            'await',
            'yield',
            'try',
            'catch',
            'finally',
            'throw',
            'typeof',
            'instanceof',
            'in',
            'of',
            'delete',
            'void',
        ],
        builtins: [
            'console',
            'window',
            'document',
            'Math',
            'JSON',
            'Object',
            'Array',
            'Promise',
            'Map',
            'Set',
            'Date',
            'RegExp',
            'process',
            'require',
            'module',
        ],
        constants: [...BOOLEANS, 'undefined', 'NaN', 'Infinity'],
    },
    {
        id: 'typescript',
        name: 'TypeScript',
        extensions: ['ts', 'tsx', 'mts', 'cts'],
        ...slashComments,
        quotes: ['"', "'", '`'],
        escapes: true,
        keywords: [
            ...C_LIKE,
            ...ACCESS,
            'const',
            'let',
            'var',
            'function',
            'class',
            'interface',
            'type',
            'enum',
            'namespace',
            'declare',
            'extends',
            'implements',
            'new',
            'this',
            'super',
            'import',
            'export',
            'from',
            'as',
            'async',
            'await',
            'yield',
            'try',
            'catch',
            'finally',
            'throw',
            'typeof',
            'instanceof',
            'keyof',
            'in',
            'of',
            'satisfies',
        ],
        types: ['string', 'number', 'boolean', 'any', 'unknown', 'never', 'void', 'object', 'symbol', 'bigint'],
        constants: [...BOOLEANS, 'undefined'],
    },
    {
        id: 'python',
        name: 'Python',
        extensions: ['py', 'pyw', 'pyi', 'bzl'],
        filenames: [/^(BUCK|BUILD)$/],
        ...hashComment,
        quotes: ['"', "'"],
        multilineQuotes: ['"""', "'''"],
        escapes: true,
        keywords: [
            'def',
            'class',
            'return',
            'if',
            'elif',
            'else',
            'for',
            'while',
            'break',
            'continue',
            'pass',
            'import',
            'from',
            'as',
            'try',
            'except',
            'finally',
            'raise',
            'with',
            'lambda',
            'global',
            'nonlocal',
            'yield',
            'assert',
            'del',
            'and',
            'or',
            'not',
            'in',
            'is',
            'async',
            'await',
        ],
        builtins: [
            'print',
            'len',
            'range',
            'open',
            'str',
            'int',
            'float',
            'list',
            'dict',
            'set',
            'tuple',
            'self',
            'super',
            'isinstance',
            'enumerate',
            'zip',
        ],
        constants: ['True', 'False', 'None'],
    },
    {
        id: 'php',
        name: 'PHP',
        extensions: ['php', 'php3', 'php4', 'php5', 'php7', 'php8', 'phtml'],
        lineComment: ['//', '#'],
        blockComment: ['/*', '*/'],
        quotes: ['"', "'"],
        escapes: true,
        identifier: /\$?[A-Za-z_][\w]*/y,
        keywords: [
            ...C_LIKE,
            ...ACCESS,
            'function',
            'class',
            'interface',
            'trait',
            'extends',
            'implements',
            'new',
            'echo',
            'print',
            'require',
            'require_once',
            'include',
            'include_once',
            'namespace',
            'use',
            'try',
            'catch',
            'finally',
            'throw',
            'foreach',
            'as',
            'match',
            'fn',
            'global',
            'instanceof',
            'yield',
        ],
        types: ['int', 'float', 'string', 'bool', 'array', 'object', 'callable', 'iterable', 'mixed', 'void'],
        constants: ['true', 'false', 'null', '$this'],
        caseInsensitive: true,
    },
    {
        id: 'ruby',
        name: 'Ruby',
        extensions: ['rb', 'rake', 'gemspec'],
        filenames: [/^(Gemfile|Rakefile)$/],
        ...hashComment,
        ...quotes,
        keywords: [
            'def',
            'end',
            'class',
            'module',
            'if',
            'elsif',
            'else',
            'unless',
            'case',
            'when',
            'while',
            'until',
            'for',
            'do',
            'begin',
            'rescue',
            'ensure',
            'return',
            'yield',
            'require',
            'attr_accessor',
            'self',
        ],
        constants: ['true', 'false', 'nil'],
    },
    {
        id: 'perl',
        name: 'Perl',
        extensions: ['pl', 'pm'],
        ...hashComment,
        ...quotes,
        identifier: /[$@%]?[A-Za-z_]\w*/y,
        keywords: [
            'sub',
            'my',
            'our',
            'local',
            'if',
            'elsif',
            'else',
            'unless',
            'while',
            'until',
            'for',
            'foreach',
            'do',
            'return',
            'use',
            'package',
            'require',
        ],
    },

    // ---- Compiled ----------------------------------------------------------
    {
        id: 'c',
        name: 'C',
        extensions: ['c', 'h', 'ino'],
        ...slashComments,
        ...quotes,
        keywords: [
            ...C_LIKE,
            'struct',
            'union',
            'enum',
            'typedef',
            'sizeof',
            'static',
            'extern',
            'const',
            'volatile',
            'inline',
            'register',
        ],
        types: ['int', 'char', 'float', 'double', 'void', 'long', 'short', 'unsigned', 'signed', 'size_t', 'bool'],
        constants: ['NULL', 'true', 'false'],
    },
    {
        id: 'cpp',
        name: 'C++',
        extensions: ['cpp', 'cc', 'cxx', 'c++', 'hpp', 'hh', 'hxx', 'h++'],
        ...slashComments,
        ...quotes,
        keywords: [
            ...C_LIKE,
            ...ACCESS,
            'class',
            'struct',
            'union',
            'enum',
            'namespace',
            'using',
            'template',
            'typename',
            'new',
            'delete',
            'this',
            'try',
            'catch',
            'throw',
            'operator',
            'virtual',
            'override',
            'constexpr',
            'nullptr_t',
            'friend',
            'explicit',
        ],
        types: [
            'int',
            'char',
            'float',
            'double',
            'void',
            'long',
            'short',
            'unsigned',
            'signed',
            'bool',
            'auto',
            'size_t',
            'string',
            'vector',
            'map',
        ],
        constants: ['nullptr', 'true', 'false', 'NULL'],
    },
    {
        id: 'csharp',
        name: 'C#',
        extensions: ['cs', 'csx'],
        ...slashComments,
        ...quotes,
        keywords: [
            ...C_LIKE,
            ...ACCESS,
            'class',
            'struct',
            'interface',
            'enum',
            'namespace',
            'using',
            'new',
            'this',
            'base',
            'try',
            'catch',
            'finally',
            'throw',
            'async',
            'await',
            'var',
            'foreach',
            'in',
            'is',
            'as',
            'get',
            'set',
            'override',
            'virtual',
            'sealed',
            'partial',
            'record',
        ],
        types: [
            'int',
            'string',
            'bool',
            'double',
            'float',
            'decimal',
            'char',
            'byte',
            'long',
            'short',
            'object',
            'void',
            'dynamic',
            'Task',
            'List',
            'Dictionary',
        ],
        constants: ['true', 'false', 'null'],
    },
    {
        id: 'java',
        name: 'Java',
        // Every Minecraft plugin ships as one of these.
        extensions: ['java'],
        ...slashComments,
        ...quotes,
        keywords: [
            ...C_LIKE,
            ...ACCESS,
            'class',
            'interface',
            'enum',
            'extends',
            'implements',
            'package',
            'import',
            'new',
            'this',
            'super',
            'try',
            'catch',
            'finally',
            'throw',
            'throws',
            'synchronized',
            'volatile',
            'transient',
            'instanceof',
            'native',
        ],
        types: [
            'int',
            'long',
            'short',
            'byte',
            'char',
            'float',
            'double',
            'boolean',
            'void',
            'String',
            'Object',
            'List',
            'Map',
        ],
        constants: ['true', 'false', 'null'],
    },
    {
        id: 'kotlin',
        name: 'Kotlin',
        extensions: ['kt', 'kts'],
        ...slashComments,
        quotes: ['"', "'"],
        multilineQuotes: ['"""'],
        escapes: true,
        keywords: [
            ...C_LIKE,
            'fun',
            'val',
            'var',
            'class',
            'object',
            'interface',
            'data',
            'sealed',
            'when',
            'is',
            'in',
            'as',
            'import',
            'package',
            'override',
            'suspend',
            'companion',
            'init',
            'try',
            'catch',
            'finally',
            'throw',
        ],
        types: ['Int', 'Long', 'Float', 'Double', 'Boolean', 'String', 'Char', 'Any', 'Unit', 'Nothing', 'List', 'Map'],
        constants: ['true', 'false', 'null'],
    },
    {
        id: 'go',
        name: 'Go',
        extensions: ['go'],
        ...slashComments,
        quotes: ['"', "'", '`'],
        escapes: true,
        keywords: [
            ...C_LIKE,
            'func',
            'var',
            'const',
            'type',
            'struct',
            'interface',
            'package',
            'import',
            'go',
            'defer',
            'chan',
            'select',
            'range',
            'map',
            'fallthrough',
        ],
        types: [
            'int',
            'int8',
            'int16',
            'int32',
            'int64',
            'uint',
            'uint8',
            'uint64',
            'float32',
            'float64',
            'string',
            'bool',
            'byte',
            'rune',
            'error',
            'any',
        ],
        constants: ['true', 'false', 'nil', 'iota'],
    },
    {
        id: 'rust',
        name: 'Rust',
        extensions: ['rs'],
        ...slashComments,
        ...quotes,
        keywords: [
            ...C_LIKE,
            'fn',
            'let',
            'mut',
            'const',
            'static',
            'struct',
            'enum',
            'trait',
            'impl',
            'mod',
            'use',
            'pub',
            'crate',
            'self',
            'super',
            'match',
            'move',
            'ref',
            'where',
            'async',
            'await',
            'dyn',
            'unsafe',
            'loop',
        ],
        types: [
            'i8',
            'i16',
            'i32',
            'i64',
            'i128',
            'u8',
            'u16',
            'u32',
            'u64',
            'u128',
            'usize',
            'isize',
            'f32',
            'f64',
            'bool',
            'char',
            'str',
            'String',
            'Vec',
            'Option',
            'Result',
        ],
        constants: ['true', 'false', 'None', 'Some', 'Ok', 'Err'],
    },
    {
        id: 'swift',
        name: 'Swift',
        extensions: ['swift'],
        ...slashComments,
        ...quotes,
        keywords: [
            ...C_LIKE,
            'func',
            'let',
            'var',
            'class',
            'struct',
            'enum',
            'protocol',
            'extension',
            'import',
            'guard',
            'defer',
            'init',
            'deinit',
            'self',
            'super',
            'throws',
            'try',
            'catch',
            'where',
            'associatedtype',
            'typealias',
        ],
        types: [
            'Int',
            'Double',
            'Float',
            'String',
            'Bool',
            'Character',
            'Array',
            'Dictionary',
            'Set',
            'Any',
            'Void',
            'Optional',
        ],
        constants: ['true', 'false', 'nil'],
    },
    {
        id: 'scala',
        name: 'Scala',
        extensions: ['scala', 'sc'],
        ...slashComments,
        quotes: ['"', "'"],
        multilineQuotes: ['"""'],
        escapes: true,
        keywords: [
            ...C_LIKE,
            'def',
            'val',
            'var',
            'class',
            'object',
            'trait',
            'extends',
            'with',
            'import',
            'package',
            'match',
            'case',
            'implicit',
            'lazy',
            'sealed',
            'override',
            'yield',
        ],
        types: ['Int', 'Long', 'Double', 'Float', 'String', 'Boolean', 'Unit', 'Any', 'List', 'Map', 'Option'],
        constants: ['true', 'false', 'null', 'None'],
    },
    {
        id: 'dart',
        name: 'Dart',
        extensions: ['dart'],
        ...slashComments,
        ...quotes,
        keywords: [
            ...C_LIKE,
            'class',
            'extends',
            'implements',
            'mixin',
            'import',
            'export',
            'library',
            'part',
            'var',
            'final',
            'const',
            'late',
            'async',
            'await',
            'yield',
            'new',
            'this',
            'super',
            'try',
            'catch',
            'finally',
            'throw',
            'factory',
        ],
        types: ['int', 'double', 'num', 'String', 'bool', 'List', 'Map', 'Set', 'void', 'dynamic', 'Future'],
        constants: ['true', 'false', 'null'],
    },
    {
        id: 'zig',
        name: 'Zig',
        extensions: ['zig'],
        lineComment: ['//'],
        ...quotes,
        keywords: [
            ...C_LIKE,
            'fn',
            'const',
            'var',
            'pub',
            'struct',
            'enum',
            'union',
            'try',
            'catch',
            'defer',
            'errdefer',
            'comptime',
            'inline',
            'orelse',
            'unreachable',
            'test',
        ],
        types: [
            'i8',
            'i16',
            'i32',
            'i64',
            'u8',
            'u16',
            'u32',
            'u64',
            'usize',
            'isize',
            'f32',
            'f64',
            'bool',
            'void',
            'type',
            'anytype',
        ],
        constants: ['true', 'false', 'null', 'undefined'],
    },

    // ---- Web ---------------------------------------------------------------
    {
        id: 'html',
        name: 'HTML',
        extensions: ['html', 'htm', 'xhtml', 'vue', 'svelte', 'hbs', 'handlebars', 'twig', 'blade'],
        blockComment: ['<!--', '-->'],
        ...quotes,
        keywords: [
            'html',
            'head',
            'body',
            'div',
            'span',
            'script',
            'style',
            'link',
            'meta',
            'title',
            'a',
            'p',
            'img',
            'form',
            'input',
            'button',
            'table',
            'ul',
            'li',
        ],
        caseInsensitive: true,
    },
    {
        id: 'xml',
        name: 'XML',
        extensions: ['xml', 'xsl', 'xsd', 'svg', 'plist', 'rss', 'wsdl', 'pom'],
        blockComment: ['<!--', '-->'],
        ...quotes,
    },
    {
        id: 'css',
        name: 'CSS',
        extensions: ['css'],
        blockComment: ['/*', '*/'],
        ...quotes,
        keywords: [
            'color',
            'background',
            'display',
            'position',
            'margin',
            'padding',
            'border',
            'width',
            'height',
            'flex',
            'grid',
            'font',
            'transition',
            'transform',
        ],
        constants: ['none', 'auto', 'inherit', 'initial', 'unset', 'absolute', 'relative', 'fixed', 'block', 'inline'],
        caseInsensitive: true,
    },
    {
        id: 'scss',
        name: 'SCSS / Less',
        extensions: ['scss', 'sass', 'less', 'styl'],
        ...slashComments,
        ...quotes,
        identifier: /[@$]?[A-Za-z_-][\w-]*/y,
        keywords: [
            '@mixin',
            '@include',
            '@extend',
            '@import',
            '@use',
            '@media',
            '@if',
            '@else',
            '@each',
            '@for',
            '@function',
            '@return',
        ],
    },

    // ---- Data and docs -----------------------------------------------------
    {
        id: 'sql',
        name: 'SQL',
        extensions: ['sql', 'ddl', 'cql'],
        lineComment: ['--', '#'],
        blockComment: ['/*', '*/'],
        ...quotes,
        keywords: [
            'select',
            'from',
            'where',
            'insert',
            'into',
            'values',
            'update',
            'set',
            'delete',
            'create',
            'alter',
            'drop',
            'table',
            'index',
            'view',
            'join',
            'inner',
            'left',
            'right',
            'outer',
            'on',
            'group',
            'order',
            'by',
            'having',
            'limit',
            'offset',
            'union',
            'distinct',
            'as',
            'and',
            'or',
            'not',
            'in',
            'like',
            'between',
            'exists',
            'primary',
            'foreign',
            'key',
            'references',
            'constraint',
            'default',
            'grant',
            'revoke',
        ],
        types: [
            'int',
            'integer',
            'bigint',
            'smallint',
            'varchar',
            'char',
            'text',
            'boolean',
            'date',
            'datetime',
            'timestamp',
            'decimal',
            'float',
            'double',
            'blob',
            'json',
        ],
        constants: ['null', 'true', 'false'],
        caseInsensitive: true,
    },
    {
        id: 'markdown',
        name: 'Markdown',
        extensions: ['md', 'markdown', 'mkd', 'mdx', 'rst'],
        quotes: ['`'],
        escapes: false,
    },
    {
        id: 'diff',
        name: 'Diff',
        extensions: ['diff', 'patch'],
        lineComment: ['---', '+++', '@@'],
    },
    {
        id: 'log',
        name: 'Log',
        // Not a language, but log files are the most opened thing in any panel
        // and picking out levels and quoted strings genuinely helps.
        extensions: ['log', 'out', 'err'],
        quotes: ['"', "'"],
        keywords: ['ERROR', 'FATAL', 'SEVERE', 'WARN', 'WARNING'],
        builtins: ['INFO', 'DEBUG', 'TRACE'],
        caseInsensitive: false,
    },
    {
        id: 'graphql',
        name: 'GraphQL',
        extensions: ['graphql', 'gql'],
        ...hashComment,
        quotes: ['"'],
        escapes: true,
        keywords: [
            'query',
            'mutation',
            'subscription',
            'fragment',
            'on',
            'type',
            'input',
            'enum',
            'interface',
            'union',
            'scalar',
            'schema',
            'extend',
            'implements',
        ],
        types: ['Int', 'Float', 'String', 'Boolean', 'ID'],
    },
    {
        id: 'protobuf',
        name: 'Protocol Buffers',
        extensions: ['proto'],
        ...slashComments,
        quotes: ['"', "'"],
        escapes: true,
        keywords: [
            'syntax',
            'package',
            'import',
            'message',
            'enum',
            'service',
            'rpc',
            'returns',
            'repeated',
            'optional',
            'required',
            'oneof',
            'map',
            'reserved',
        ],
        types: ['double', 'float', 'int32', 'int64', 'uint32', 'uint64', 'bool', 'string', 'bytes'],
    },
    {
        id: 'plaintext',
        name: 'Plain Text',
        extensions: ['txt', 'text', 'list', 'def'],
    },
];

export default languages;

const byId = new Map(languages.map((language) => [language.id, language]));

export const plaintext = byId.get('plaintext')!;

export const languageById = (id: string): LanguageSpec => byId.get(id) ?? plaintext;

/**
 * Picks a language for a filename. Exact filename patterns win over extensions,
 * so Dockerfile beats the extensionless fallback.
 */
export const languageForFilename = (filename: string): LanguageSpec => {
    const name = filename.split(/[\\/]/).pop() ?? filename;

    for (const language of languages) {
        if (language.filenames?.some((pattern) => pattern.test(name))) {
            return language;
        }
    }

    const dot = name.lastIndexOf('.');
    if (dot > -1) {
        const extension = name.slice(dot + 1).toLowerCase();
        const match = languages.find((language) => language.extensions.includes(extension));

        if (match) return match;
    }

    // Some files are all extension and no name: ".env", ".bashrc".
    if (name.startsWith('.')) {
        const bare = name.slice(1).toLowerCase();
        const match = languages.find((language) => language.extensions.includes(bare));

        if (match) return match;
    }

    return plaintext;
};

/** Every language, sorted for display in a picker. */
export const sortedLanguages = (): LanguageSpec[] => [...languages].sort((a, b) => a.name.localeCompare(b.name));

/** Substring search over name, id and extensions, for the language picker. */
export const searchLanguages = (query: string): LanguageSpec[] => {
    const needle = query.trim().toLowerCase();

    if (!needle) return sortedLanguages();

    return sortedLanguages().filter(
        (language) =>
            language.name.toLowerCase().includes(needle) ||
            language.id.includes(needle) ||
            language.extensions.some((extension) => extension.includes(needle))
    );
};
